services:
  auth-mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - auth-data:/data/db

  auth-app:
    build: ./auth-service
    depends_on:
      - auth-mongo
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://auth-mongo:27017/auth

volumes:
  auth-data:
